#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Nov 11 10:21:37 PST 2025
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=12
shaderPack=ComplementaryReimagined_r5.6.1.zip
enableShaders=true
