name = "KatKraft"
author = "SugoiDogo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0dc03b0a7cb25f8a6b30ae3604f9197c7fa7aa8f76fe19ef61d817a7ca9dbdb5"

[versions]
forge = "43.2.14"
minecraft = "1.19.2"
