name = "KatCraft"
author = "SugoiDogo"
version = "2.0.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "534e9aec34b21d420971271ed406e0c797f94e082f413ccf5b98ec4c6bd4fc86"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
