name = "KatCraft"
author = "SugoiDogo"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7199bcd54e57e3fd3b8b6c1ab9b011280bdc05c01f157a61a3d5048ec8db2c2"

[versions]
forge = "47.4.0"
minecraft = "1.20.1"
